name: hamlog
description: Library for processing Amateur Radio logs.
version: 0.0.1
author: Mike Karas <mike.om4aa@gmail.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  intl: '>=0.11.9'
#  lib_name: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
